# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
#  apt_packages:
#    - man-db
#    - build-essential
#    - wget
#    - autotools-dev
#    - automake
#    - python3-dev
#    - python3-setuptools
#  jobs:
#    post_system_dependencies:
#      - export ION_HOME=$(pwd)/ion-open-source-4.1.2
#      - export PYION_HOME=$(pwd)
#      - export PYION_BP_VERSION=BPv7
#      - wget https://sourceforge.net/projects/ion-dtn/files/ion-open-source-4.1.2.tar.gz
#      - tar -xvzf ion-open-source-4.1.2.tar.gz
#      - cp -a ./ion-open-source-4.1.2/. .
#      - ls -l
#      - ./configure
#      - make
#      - make install
#      - python setup.py install

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
    - method: setuptools
      path: .