# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - man-db
    - build-essential
    - wget
    - autotools-dev
    - automake
    - python3-dev
    - python3-setuptools
  jobs:
    pre_create_environment:
      - wget https://sourceforge.net/projects/ion-dtn/files/ion-open-source-4.1.2.tar.gz
      - tar -xvzf ion-open-source-4.1.2.tar.gz
      - cd ./ion-open-source-4.1.2
      - ./configure
      - make
      - make install


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
    - method: setuptools
      path: .